### PR TITLE
fix: only listen for the 'storage' event if using 'local' storage

### LINKED ISSUE #150: PersistedState: Adds storage event listener without regards of the type of storage
### Describe the bug

By looking at the code, it seems that the store will listen to 'storage' events even when the storage is not 'local'.  This would then leak local storage values into session storage when the key matches.

### Reproduction

Not needed?

### Logs

_No response_

### System Info

```bash
Doesn't matter
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by webJose**
Fixes #150.

## Notes

jsdom doesn't raise the 'storage' event because this event only fires when values change **in a different** window, which is something we don't have (we only have one window).  So to unit-test, one must dispatch the event manually.

Also:  The event handler uses `getValueFromStorage` to obtain the value, but the `event.newValue` property already has this value.  This seems like an unnecessary performance hit, and may be best to simply deserialize `event.newValue`.

### New Situation/Issue

I noticed that there is no deletion.  I think that whenever `this.#current` becomes undefined, the value in storage should be deleted.

### CODE REVIEW

**Comment by webJose** [comment]
Two more things:  Unsure if there's anything else required, so I made this a draft PR.  The second is that I added the `delay()` function to the testing helpers so as to not continuously drag the timeout thing in a new promise every time one must await for effects to run.

File: packages/runed/src/lib/test/util.svelte.ts [hunk 1]
```diff
@@ -29,3 +29,7 @@ export function focus(node: HTMLElement | null | undefined) {
 		flushSync(() => node.focus());
 	}
 }
+
+export function delay(timeout = 0) {
```
Comment (huntabyte) [inline packages/runed/src/lib/test/util.svelte.ts:33]: I believe we have a `sleep` util already that does this exact thing!

Comment (webJose) [reply packages/runed/src/lib/test/util.svelte.ts:33]: I made this because I saw no such thing being used in the existing unit tests. If it exists, I can remove this one.  It would be nice, then, if the unit tests were updated at some point to use this sleep function instead of what's being done now, for consistency.

I'll look that sleep function up.

Comment (webJose) [reply packages/runed/src/lib/test/util.svelte.ts:33]: Found it.  Can I improve it by making the parameter optional with a value of zero?  As in:

```diff
- export async function sleep(ms: number): Promise<void> {
+ export async function sleep(ms = 0): Promise<void> {
    ...
}
```

Comment (huntabyte) [reply packages/runed/src/lib/test/util.svelte.ts:33]: Yes 😃

**Comment by webJose** [comment]
Done.  Let me know if there are any more pendings.  If not, I'll add a changeset and take the PR out of Draft status.

**Comment by huntabyte** [comment]
Feel free to move it out of draft @webJose !

**Comment by huntabyte** [comment]
Thank you!

**Review by huntabyte — APPROVED** [review]

**Comment by webJose** [comment]
Ha, you were in a hurry.  I came but the branch was merged already.
