### PR TITLE
fix PersistedState: it no longer console errors if `typeof window === undefined`

### LINKED ISSUE #241: SyntaxError: "undefined" is not valid JSON
### Describe the bug

Throws error Error when parsing "undefined" from persisted store "greetings" SyntaxError: "undefined" is not valid JSON when storage is empty.

~Most likely this line assumes `this.#storage?.getItem(this.#key)` to be always string:~ https://github.com/svecosystem/runed/blob/c25b136f23e83584669ea6ccdf4cde8aec74b73b/packages/runed/src/lib/utilities/persisted-state/persisted-state.svelte.ts#L80

### Reproduction

https://github.com/mrwokkel/runed-persisted-state-undefined-not-valid-json

Just (p)npm dev, given the storage is empty

### Logs

```bash
From terminal:

Error when parsing "undefined" from persisted store "greetings" SyntaxError: "undefined" is not valid JSON
    at Object.parse [as deserialize] (<anonymous>)
    at #deserialize (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/node_modules/.pnpm/runed@0.25.0_svelte@5.25.3/node_modules/runed/dist/utilities/persisted-state/persisted-state.svelte.js:120:28)
    at get current [as current] (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/node_modules/.pnpm/runed@0.25.0_svelte@5.25.3/node_modules/runed/dist/utilities/persisted-state/persisted-state.svelte.js:74:33)
    at _page (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/src/routes/+page.svelte:15:61)
    at children (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/.svelte-kit/generated/root.svelte:66:5)
    at _layout (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/src/routes/+layout.svelte:13:2)
    at Root (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/.svelte-kit/generated/root.svelte:61:3)
    at render (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/node_modules/.pnpm/svelte@5.25.3/node_modules/svelte/src/internal/server/index.js:142:2)
    at Function._render [as render] (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/node_modules/.pnpm/svelte@5.25.3/node_modules/svelte/src/legacy/legacy-server.js:30:50)
    at render_response (/Users/mrwokkel/Code/mrwokkel/reproduction/runed-persisted-state-undefined-not-valid-json/node_modules/.pnpm/@sveltejs+kit@2.20.2_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.25.3_vite@6.2.3_jiti@2_bdf909ba448835cbc211c47ccad9f78d/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:132:33)
```

### System Info

```bash
System:
    OS: macOS 15.3.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.79 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 10.3.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 134.0.6998.166
    Safari: 18.3.1
  npmPackages:
    @sveltejs/kit: ^2.16.0 => 2.20.2 
    runed: ^0.25.0 => 0.25.0 
    svelte: ^5.0.0 => 5.25.3
```

### Severity

blocking an upgrade

### PR DESCRIPTION
**Pull request by aster-void**
closes #241

### CODE REVIEW

**Comment by huntabyte** [comment]
Sorry for the delay on this @aster-void , was out of town for a couple of weeks!

File: packages/runed/src/lib/utilities/persisted-state/persisted-state.svelte.ts [hunk 1]
```diff
@@ -48,8 +48,8 @@ export class PersistedState<T> {
 			storage: storageType = "local",
 			serializer = { serialize: JSON.stringify, deserialize: JSON.parse },
 			syncTabs = true,
-			window = defaultWindow,
 		} = options;
+		const window = "window" in options ? options.window : defaultWindow; // window is not mockable to be undefined without this, because JavaScript will fill undefined with `= default`
```
Comment (huntabyte) [inline packages/runed/src/lib/utilities/persisted-state/persisted-state.svelte.ts:52]: Ah I bet we'll probably need to do this for some other utilities as well then 😃

**Review by huntabyte — APPROVED** [review]
Thank you!
